# 딕셔너리

In [30]:
A = {"사과" : "열매"}

In [31]:
print(A)
print(type(A))

{'사과': '열매'}
<class 'dict'>


In [32]:
A.keys()

dict_keys(['사과'])

In [33]:
A.values()

dict_values(['열매'])

In [34]:
A = {1 : 1}
print(A)
print(type(A))

{1: 1}
<class 'dict'>


In [35]:
A = {1.0 : 1}
print(A)
print(type(A))

{1.0: 1}
<class 'dict'>


In [36]:
A.keys()

dict_keys([1.0])

In [37]:
print(type(1j))

<class 'complex'>


In [38]:
print(1j * 1j)

(-1+0j)


In [39]:
A = {True : 1}
print(A)
print(type(A))

{True: 1}
<class 'dict'>


In [40]:
A.keys()

dict_keys([True])

In [41]:
import numpy as np

In [75]:
W = np.array([[1, 1],
                [1, 1]])
print(W)

[[1 1]
 [1 1]]


In [76]:
b = {'b' : 1}
a = {'a' : b}
print(b)
print(a)

{'b': 1}
{'a': {'b': 1}}


In [77]:
a.keys()

dict_keys(['a'])

In [78]:
a.values()

dict_values([{'b': 1}])

In [79]:
A = {'W':W}
print(A)

{'W': array([[1, 1],
       [1, 1]])}


In [80]:
A['W']

array([[1, 1],
       [1, 1]])

In [81]:
lr = 0.01
A_grad = np.array([[1, 1],
                   [1, 1]])
A['W'] = A['W'] - lr * A_grad
print(A['W'])

[[0.99 0.99]
 [0.99 0.99]]


In [68]:
w = np.random.randn(10)
print(w)

[-0.53486958 -0.22632471 -1.70860438  0.13219631  1.09690531 -0.31755121
  0.67230691 -0.67096629 -1.05242454 -0.12387215]


In [89]:
W1 = np.random.randn(2, 2)
print(w1)
print(np.shape(w1))

[[ 0.15352545  1.23644483]
 [-0.71989823 -1.19055697]]
(2, 2)


In [84]:
b1 = np.zeros(2)
print(b1)

[0. 0.]


In [85]:
W2 = np.random.randn(2, 1)
print(W2)

[[-1.08981195]
 [ 2.41354454]]


In [87]:
b2 = np.zeros(1)
print(b2)

[0.]


In [90]:
A = {'W1' : W1,
     'b1' : b1,
     'W2' : W2,
     'b2' : b2}
print(A)

{'W1': array([[1.96200805, 0.10129621],
       [0.4288531 , 1.26486479]]), 'b1': array([0., 0.]), 'W2': array([[-1.08981195],
       [ 2.41354454]]), 'b2': array([0.])}


In [91]:
A['W1']

array([[1.96200805, 0.10129621],
       [0.4288531 , 1.26486479]])

In [92]:
lr

0.01

In [95]:
A['W1'] = A['W1'] - lr * A['W1']
A['b1'] = A['b1'] - lr * A['b1']
A['W2'] = A['W2'] - lr * A['W2']
A['b2'] = A['b2'] - lr * A['b2']
print(A['W1'])
print(A['b1'])
print(A['W2'])
print(A['b2'])

[[1.90373445 0.09828761]
 [0.41611574 1.22729704]]
[0. 0.]
[[-1.0681247]
 [ 2.365515 ]]
[0.]


In [96]:
A['W1'][0,0]
# T = A['W1'] * 

1.9037344467808022

# 미분

In [99]:
x0 = 3
y = x0**2
print(y)

9


In [100]:
dy = 2 * x0
print(dy)

6


In [101]:
y = 0
z = 1 / (1 + np.exp(-y))
print(z)

0.5


In [102]:
dy = z * (1 - z)
print(dy)

0.25
