In [1]:
A = {"사과" : "열매"}

In [2]:
print(A)
print(type(A))

{'사과': '열매'}
<class 'dict'>


In [3]:
A.keys()

dict_keys(['사과'])

In [4]:
A.values()

dict_values(['열매'])

In [5]:
A = { 1 : 1 }
print(A)
print(type(A))

{1: 1}
<class 'dict'>


In [6]:
A = { 1.0 : 1 }
print(A)
print(type(A))

{1.0: 1}
<class 'dict'>


In [7]:
A.keys()

dict_keys([1.0])

In [9]:
print(type(1j))

<class 'complex'>


In [10]:
print(1j * 1j)

(-1+0j)


In [11]:
A = {True : 1}
print(A)

{True: 1}


In [12]:
A.keys()

dict_keys([True])

In [13]:
import numpy as np

In [14]:
W = np.array([[1, 1],
              [1, 1]])
print(W)

[[1 1]
 [1 1]]


In [15]:
A = {'W' : W}
print(A)

{'W': array([[1, 1],
       [1, 1]])}


In [16]:
b = {'b' : 1}
a = {'a' : b}
print(a)

{'a': {'b': 1}}


In [17]:
A.keys()

dict_keys(['W'])

In [18]:
A.values()

dict_values([array([[1, 1],
       [1, 1]])])

In [19]:
A['W']

array([[1, 1],
       [1, 1]])

In [20]:
A['W'] = np.array([[2, 2],
                   [2, 2]])
print(A)

{'W': array([[2, 2],
       [2, 2]])}


In [22]:
lr = 0.01
A_grad = np.array([[1, 1],
                   [1, 1]])
A['W'] = A['W'] - lr * A_grad
print(A['W'])

[[0.99 0.99]
 [0.99 0.99]]


In [30]:
w = np.random.randn(10)
print(w)

[ 1.09670311 -1.93089369  0.82314708 -1.97193152 -0.20805222  0.3112718
  1.6691314   0.42937724 -1.78261069  0.3013037 ]


In [32]:
W1 = np.random.randn(2,2)
print(W1)
print(np.shape(W1))

[[-0.87421712 -2.39541124]
 [ 0.19663443 -0.16899527]]
(2, 2)


In [33]:
b1 = np.zeros(2)
print(b1)

[0. 0.]


In [34]:
W2 = np.random.randn(2,1)
print(W2)

[[0.60980846]
 [1.34637558]]


In [35]:
b2 = np.zeros(1)
print(b2)

[0.]


In [36]:
A = {'W1' : W1,
    'b1' : b1,
    'W2' : W2,
    'b2' : b2}
print(A)

{'W1': array([[-0.87421712, -2.39541124],
       [ 0.19663443, -0.16899527]]), 'b1': array([0., 0.]), 'W2': array([[0.60980846],
       [1.34637558]]), 'b2': array([0.])}


In [37]:
A['W1']

array([[-0.87421712, -2.39541124],
       [ 0.19663443, -0.16899527]])

In [38]:
lr

0.01

In [40]:
A['W1'] = A['W1'] - lr * A['W1']
A['b1'] = A['b1'] - lr * A['b1']
A['W2'] = A['W2'] - lr * A['W2']
A['b2'] = A['b2'] - lr * A['b2']

print(A['W1'])
print(A['b1'])
print(A['W2'])
print(A['b2'])

[[-0.8568202  -2.34774255]
 [ 0.19272141 -0.16563226]]
[0. 0.]
[[0.59767328]
 [1.3195827 ]]
[0.]


In [42]:
A['W1'][0,0]

-0.8568202042045778

# 미분

In [45]:
x0 = 3
y = x0**2
print(y)

9


In [46]:
dy = 2*x0
print(dy)

6


In [47]:
y = 0
z = 1 / (1 + np.exp(-y))
print(z)

0.5


In [48]:
dy = z * (1- z)
print(dy)

0.25


In [50]:
x = 1
w = 1
b = 0

y = x*w + b
print(y)

1


In [51]:
dx = w
dw = x
db = 1

In [54]:
x = 2
t = 1
lr =0.01

w = np.random.randn(1)
b = 0

for i in range(100):
    # Forward
    y = w * x + b
    L = (y - t)**2
    print("{} th y 값 : {} ".format(i, y))
    print("{} th L 값 : {} ".format(i, L))
    
    # Gradient / Backpropagation
    dL_dy = 2 * (y-t)
    dy_dw = x
    dy_db = 1
    
    dw = dL_dy * dy_dw
    db = dL_dy * dy_db
    
    # Update
    w = w - lr * dw
    b = b - lr * db

y = w * x + b
L = (y-t)**2
print(y)
print(L)

0 th y 값 : [-1.56792853] 
0 th L 값 : [6.59425692] 
1 th y 값 : [-1.31113568] 
1 th L 값 : [5.34134811] 
2 th y 값 : [-1.08002211] 
2 th L 값 : [4.32649197] 
3 th y 값 : [-0.8720199] 
3 th L 값 : [3.50445849] 
4 th y 값 : [-0.68481791] 
4 th L 값 : [2.83861138] 
5 th y 값 : [-0.51633612] 
5 th L 값 : [2.29927522] 
6 th y 값 : [-0.3647025] 
6 th L 값 : [1.86241293] 
7 th y 값 : [-0.22823225] 
7 th L 값 : [1.50855447] 
8 th y 값 : [-0.10540903] 
8 th L 값 : [1.22192912] 
9 th y 값 : [0.00513187] 
9 th L 값 : [0.98976259] 
10 th y 값 : [0.10461869] 
10 th L 값 : [0.8017077] 
11 th y 값 : [0.19415682] 
11 th L 값 : [0.64938323] 
12 th y 값 : [0.27474114] 
12 th L 값 : [0.52600042] 
13 th y 값 : [0.34726702] 
13 th L 값 : [0.42606034] 
14 th y 값 : [0.41254032] 
14 th L 값 : [0.34510888] 
15 th y 값 : [0.47128629] 
15 th L 값 : [0.27953819] 
16 th y 값 : [0.52415766] 
16 th L 값 : [0.22642593] 
17 th y 값 : [0.57174189] 
17 th L 값 : [0.18340501] 
18 th y 값 : [0.6145677] 
18 th L 값 : [0.14855805] 
19 th y 값 : [0.65311093] 
1

In [ ]:
A = {"사과" : "열매"}

print(A)
print(type(A))

A.keys()

A.values()

A = { 1 : 1 }
print(A)
print(type(A))

A = { 1.0 : 1 }
print(A)
print(type(A))

A.keys()

print(type(1j))

print(1j * 1j)

A = {True : 1}
print(A)

A.keys()

import numpy as np

W = np.array([[1, 1],
              [1, 1]])
print(W)

A = {'W' : W}
print(A)

b = {'b' : 1}
a = {'a' : b}
print(a)

A.keys()

A.values()

A['W']

A['W'] = np.array([[2, 2],
                   [2, 2]])
print(A)

lr = 0.01
A_grad = np.array([[1, 1],
                   [1, 1]])
A['W'] = A['W'] - lr * A_grad
print(A['W'])

w = np.random.randn(10)
print(w)

W1 = np.random.randn(2,2)
print(W1)
print(np.shape(W1))

b1 = np.zeros(2)
print(b1)

W2 = np.random.randn(2,1)
print(W2)

b2 = np.zeros(1)
print(b2)

A = {'W1' : W1,
    'b1' : b1,
    'W2' : W2,
    'b2' : b2}
print(A)

A['W1']

lr

A['W1'] = A['W1'] - lr * A['W1']
A['b1'] = A['b1'] - lr * A['b1']
A['W2'] = A['W2'] - lr * A['W2']
A['b2'] = A['b2'] - lr * A['b2']

print(A['W1'])
print(A['b1'])
print(A['W2'])
print(A['b2'])

A['W1'][0,0]

# 미분

x0 = 3
y = x0**2
print(y)

dy = 2*x0
print(dy)

y = 0
z = 1 / (1 + np.exp(-y))
print(z)

dy = z * (1- z)
print(dy)

x = 1
w = 1
b = 0

y = x*w + b
print(y)

dx = w
dw = x
db = 1

x = 2
t = 1
lr =0.01

w = np.random.randn(1)
b = 0

for i in range(100):
    # Forward
    y = w * x + b
    L = (y - t)**2
    print("{} th y 값 : {} ".format(i, y))
    print("{} th L 값 : {} ".format(i, L))
    
    # Gradient / Backpropagation
    dL_dy = 2 * (y-t)
    dy_dw = x
    dy_db = 1
    
    dw = dL_dy * dy_dw
    db = dL_dy * dy_db
    
    # Update
    w = w - lr * dw
    b = b - lr * db

y = w * x + b
L = (y-t)**2
print(y)
print(L)



# 0429

In [5]:
import numpy as np

In [13]:
x = 2
t = 1
lr = 0.01

w = np.random.randn(1)
b = np.zeros(1)

print(w)
print(b)

[0.46071395]
[0.]


In [14]:
for i in range(100):
    y = w * x + b
    print("{} th 예측값 : {}".format(i,y))
    loss = (y - t)**2
    print("{} th 예측값 : {}".format(i,loss))
    
    dL_dy = 2 * y - 2 * t
    dy_dw = x
    dy_db = 1
    
    w_grad = dL_dy * dy_dw
    b_grad = dL_dy * dy_db
    
    w = w - lr * w_grad
    b = b - lr * b_grad
    
y = w * x + b
print(y)
print(loss)

0 th 예측값 : [0.9214279]
0 th 예측값 : [0.00617358]
1 th 예측값 : [0.92928511]
1 th 예측값 : [0.0050006]
2 th 예측값 : [0.9363566]
2 th 예측값 : [0.00405048]
3 th 예측값 : [0.94272094]
3 th 예측값 : [0.00328089]
4 th 예측값 : [0.94844884]
4 th 예측값 : [0.00265752]
5 th 예측값 : [0.95360396]
5 th 예측값 : [0.00215259]
6 th 예측값 : [0.95824356]
6 th 예측값 : [0.0017436]
7 th 예측값 : [0.96241921]
7 th 예측값 : [0.00141232]
8 th 예측값 : [0.96617729]
8 th 예측값 : [0.00114398]
9 th 예측값 : [0.96955956]
9 th 예측값 : [0.00092662]
10 th 예측값 : [0.9726036]
10 th 예측값 : [0.00075056]
11 th 예측값 : [0.97534324]
11 th 예측값 : [0.00060796]
12 th 예측값 : [0.97780892]
12 th 예측값 : [0.00049244]
13 th 예측값 : [0.98002803]
13 th 예측값 : [0.00039888]
14 th 예측값 : [0.98202522]
14 th 예측값 : [0.00032309]
15 th 예측값 : [0.9838227]
15 th 예측값 : [0.00026171]
16 th 예측값 : [0.98544043]
16 th 예측값 : [0.00021198]
17 th 예측값 : [0.98689639]
17 th 예측값 : [0.0001717]
18 th 예측값 : [0.98820675]
18 th 예측값 : [0.00013908]
19 th 예측값 : [0.98938607]
19 th 예측값 : [0.00011266]
20 th 예측값 : [0.99044747]
20

In [38]:
w = np.random.randn(1)
b = np.zeros(1)

In [39]:
param = {"w" : w,
        "b" : b}

In [17]:
print(param["w"])

[-0.73013507]


In [18]:
print(param["b"])

[0.]


In [40]:
for i in range(100):
    y = param["w"] * x + param["b"]
    print("{} th 예측값 : {}".format(i,y))
    loss = (y - t)**2
    print("{} th 예측값 : {}".format(i,loss))
    
    dL_dy = 2 * y - 2 * t
    dy_dw = x
    dy_db = 1
    
    w_grad = dL_dy * dy_dw
    b_grad = dL_dy * dy_db
    
    param["w"] = param["w"] - lr * w_grad
    param["b"] = param["b"] - lr * b_grad
    
y = param["w"] * x + param["b"]
loss = (y - t)**2
print(y)
print(loss)

0 th 예측값 : [-0.83443933]
0 th 예측값 : [3.36516765]
1 th 예측값 : [-0.6509954]
1 th 예측값 : [2.7257858]
2 th 예측값 : [-0.48589586]
2 th 예측값 : [2.2078865]
3 th 예측값 : [-0.33730627]
3 th 예측값 : [1.78838806]
4 th 예측값 : [-0.20357564]
4 th 예측값 : [1.44859433]
5 th 예측값 : [-0.08321808]
5 th 예측값 : [1.17336141]
6 th 예측값 : [0.02510373]
6 th 예측값 : [0.95042274]
7 th 예측값 : [0.12259336]
7 th 예측값 : [0.76984242]
8 th 예측값 : [0.21033402]
8 th 예측값 : [0.62357236]
9 th 예측값 : [0.28930062]
9 th 예측값 : [0.50509361]
10 th 예측값 : [0.36037056]
10 th 예측값 : [0.40912583]
11 th 예측값 : [0.4243335]
11 th 예측값 : [0.33139192]
12 th 예측값 : [0.48190015]
12 th 예측값 : [0.26842745]
13 th 예측값 : [0.53371014]
13 th 예측값 : [0.21742624]
14 th 예측값 : [0.58033912]
14 th 예측값 : [0.17611525]
15 th 예측값 : [0.62230521]
15 th 예측값 : [0.14265335]
16 th 예측값 : [0.66007469]
16 th 예측값 : [0.11554922]
17 th 예측값 : [0.69406722]
17 th 예측값 : [0.09359487]
18 th 예측값 : [0.7246605]
18 th 예측값 : [0.07581184]
19 th 예측값 : [0.75219445]
19 th 예측값 : [0.06140759]
20 th 예측값 : [0.7769

In [49]:
class 사람:
    def __init__(self, 이성):
        self.이성 = 이성
        
    def 인사(self):
        print("안녕하세요")

In [50]:
h1 = 사람(이성="냉철함")

In [51]:
h1.이성

'냉철함'

In [52]:
h1.인사()

안녕하세요
